"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./navBar";
import { useAtom } from "jotai";
import { themeAtom } from "./store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = useAtom<string>(themeAtom);
  return (
    <html data-theme={theme}>
      <body className={inter.className}>
        <nav>
          <NavBar />
        </nav>
        {children}
      </body>
    </html>
  );
}
