import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from 'react'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html data-theme="dark">
      <head>
        <title>Movie Mania</title>
        <link rel="icon" href="/favicon.ico" className="h-6 w-6" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
